env:
  browser: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
rules:
  no-console:
    - off
  no-unused-vars:
    - off
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
