# Site settings
title: "CHH"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chh.sg" # the base hostname & protocol for your site
identity: chh.sg
# Build settings
markdown: kramdown
encoding: utf-8
sass:
    style: compressed
    sass_dir: _sass
